services:
  - type: web
    name: exam-seating-portal
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: RENDER
        value: true
      - key: SECRET_KEY
        generateValue: true
    disk:
      name: data
      mountPath: /tmp
      sizeGB: 1
